USE SCHEMA FIDELITY_ATLAS.RAW;


CREATE OR REPLACE STORAGE INTEGRATION ATLAS_S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::034501260759:role/FidelityAtlasSnowflakeRole'
  STORAGE_ALLOWED_LOCATIONS = ('s3://fidelity-atlas-batch-ram-01/batch/');

DESC INTEGRATION ATLAS_S3_INT;

CREATE OR REPLACE FILE FORMAT FF_TRADES_CSV
  TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"'
  TIMESTAMP_FORMAT='YYYY-MM-DD HH24:MI:SS';

CREATE OR REPLACE STAGE ATLAS_BATCH_STAGE
  STORAGE_INTEGRATION = ATLAS_S3_INT
  URL = 's3://fidelity-atlas-batch-ram-01/batch/'
  FILE_FORMAT = FF_TRADES_CSV;

  LIST @ATLAS_BATCH_STAGE;



CREATE OR REPLACE TEMPORARY TABLE FIDELITY_ATLAS.RAW.STG_TRADES_RAW (
  TRADE_ID       VARCHAR,
  TRADE_TS       VARCHAR,
  SYMBOL         VARCHAR,
  SIDE           VARCHAR,
  QUANTITY       NUMBER,
  PRICE          NUMBER(18,4),
  VENUE_CODE     VARCHAR
);

COPY INTO FIDELITY_ATLAS.RAW.STG_TRADES_RAW
FROM @ATLAS_BATCH_STAGE
FILE_FORMAT = FF_TRADES_CSV;

INSERT INTO FIDELITY_ATLAS.ANALYTICS.FACT_TRADES
SELECT
  NULL,
  r.TRADE_ID,
  s.SECURITY_KEY,
  v.VENUE_KEY,
  TO_NUMBER(TO_CHAR(TO_TIMESTAMP_NTZ(r.TRADE_TS), 'YYYYMMDD')),
  TO_TIMESTAMP_NTZ(r.TRADE_TS),
  r.SIDE,
  r.QUANTITY,
  r.PRICE,
  (r.QUANTITY * r.PRICE)
FROM FIDELITY_ATLAS.RAW.STG_TRADES_RAW r
JOIN FIDELITY_ATLAS.ANALYTICS.DIM_SECURITY s ON s.SYMBOL = r.SYMBOL
JOIN FIDELITY_ATLAS.ANALYTICS.DIM_VENUE    v ON v.VENUE_CODE = r.VENUE_CODE;   


SELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME=>'FIDELITY_ATLAS.ANALYTICS.FACT_TRADES',
  START_TIME=>DATEADD('hour',-1,CURRENT_TIMESTAMP())));

  SELECT COUNT(*) AS trades_loaded FROM FIDELITY_ATLAS.ANALYTICS.FACT_TRADES;


