USE SCHEMA FIDELITY_ATLAS.RAW;


CREATE OR REPLACE WAREHOUSE ATLAS_ANALYTICS_WH
  WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=FALSE;
USE WAREHOUSE ATLAS_ANALYTICS_WH;


ALTER SESSION SET USE_CACHED_RESULT = FALSE;  -- so we measure real compute
SELECT SYMBOL, DATE_TRUNC('week', TRADE_DATE) AS wk,
       AVG(LAST_PRICE), MAX(ASK-BID) AS max_spread, SUM(TRADE_SIZE) AS vol
FROM TICKS_CLUSTERED
GROUP BY 1,2 ORDER BY 1,2;


ALTER WAREHOUSE ATLAS_ANALYTICS_WH SET WAREHOUSE_SIZE='MEDIUM';


ALTER WAREHOUSE ATLAS_ANALYTICS_WH SET
  WAREHOUSE_SIZE='XSMALL'
  MIN_CLUSTER_COUNT=1
  MAX_CLUSTER_COUNT=3
  SCALING_POLICY='STANDARD';


USE WAREHOUSE ATLAS_ANALYTICS_WH;
ALTER SESSION SET USE_CACHED_RESULT = FALSE;
SELECT SYMBOL, AVG(LAST_PRICE), SUM(TRADE_SIZE) AS vol,
       COUNT(*) AS ticks, MAX(ASK-BID) AS max_spread
FROM TICKS_CLUSTERED
WHERE TRADE_DATE BETWEEN '2024-01-15' AND '2024-03-15'
GROUP BY SYMBOL ORDER BY vol DESC;

SELECT * FROM TABLE(INFORMATION_SCHEMA.WAREHOUSE_LOAD_HISTORY(
  DATE_RANGE_START => DATEADD('minute',-15,CURRENT_TIMESTAMP()),
  WAREHOUSE_NAME   => 'ATLAS_ANALYTICS_WH'));


SELECT query_id, user_name, execution_status,
       queued_provisioning_time, queued_overload_time, total_elapsed_time
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY_BY_WAREHOUSE('ATLAS_ANALYTICS_WH'))
WHERE start_time > DATEADD('minute',-15,CURRENT_TIMESTAMP())
ORDER BY start_time DESC;