USE SCHEMA FIDELITY_ATLAS.RAW;


CREATE OR REPLACE TABLE RAW_TICKS_STREAM (
  SYMBOL STRING, TICK_TS TIMESTAMP_NTZ, LAST_PRICE NUMBER(12,2),
  TRADE_SIZE NUMBER(10,0), VENUE STRING,
  FILE_NAME STRING, LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE OR REPLACE FILE FORMAT FF_TICKS_CSV
  TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"'
  TIMESTAMP_FORMAT='YYYY-MM-DD HH24:MI:SS';

ALTER STORAGE INTEGRATION ATLAS_S3_INT SET STORAGE_ALLOWED_LOCATIONS =
  ('s3://fidelity-atlas-batch-ram-01/batch/',
   's3://fidelity-atlas-batch-ram-01/autoingest/');

CREATE OR REPLACE STAGE ATLAS_AUTOINGEST_STAGE
  STORAGE_INTEGRATION = ATLAS_S3_INT
  URL = 's3://fidelity-atlas-batch-ram-01/autoingest/'
  FILE_FORMAT = FF_TICKS_CSV;

CREATE OR REPLACE PIPE ATLAS_TICKS_PIPE
  AUTO_INGEST = TRUE
AS
COPY INTO RAW_TICKS_STREAM (SYMBOL,TICK_TS,LAST_PRICE,TRADE_SIZE,VENUE,FILE_NAME)
FROM (
  SELECT $1,$2,$3,$4,$5, METADATA$FILENAME
  FROM @ATLAS_AUTOINGEST_STAGE
)
FILE_FORMAT = FF_TICKS_CSV;



SHOW PIPES;


SELECT SYSTEM$PIPE_STATUS('ATLAS_TICKS_PIPE');
SELECT COUNT(*) FROM RAW_TICKS_STREAM;          -- ~2000 after first file
SELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME=>'FIDELITY_ATLAS.RAW.RAW_TICKS_STREAM',
  START_TIME=>DATEADD('hour',-1,CURRENT_TIMESTAMP())));

LIST @ATLAS_BATCH_STAGE;

DESC INTEGRATION ATLAS_S3_INT;
