USE ROLE ACCOUNTADMIN;   -- (USERADMIN/SECURITYADMIN split is the prod pattern; flag it)

-- 1) ACCESS roles — the WHAT:
CREATE ROLE IF NOT EXISTS FUIDP_RAW_READ;
CREATE ROLE IF NOT EXISTS FUIDP_ANALYTICS_READ;
CREATE ROLE IF NOT EXISTS FUIDP_ANALYTICS_RW;

GRANT USAGE ON DATABASE FUIDP TO ROLE FUIDP_RAW_READ;
GRANT USAGE ON SCHEMA FUIDP.RAW TO ROLE FUIDP_RAW_READ;
GRANT SELECT ON ALL TABLES IN SCHEMA FUIDP.RAW TO ROLE FUIDP_RAW_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FUIDP.RAW TO ROLE FUIDP_RAW_READ;  -- the silent-gap killer

GRANT USAGE ON DATABASE FUIDP TO ROLE FUIDP_ANALYTICS_READ;
GRANT USAGE ON SCHEMA FUIDP.ANALYTICS TO ROLE FUIDP_ANALYTICS_READ;
GRANT SELECT ON ALL TABLES IN SCHEMA FUIDP.ANALYTICS TO ROLE FUIDP_ANALYTICS_READ;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FUIDP.ANALYTICS TO ROLE FUIDP_ANALYTICS_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FUIDP.ANALYTICS TO ROLE FUIDP_ANALYTICS_READ;

GRANT ROLE FUIDP_ANALYTICS_READ TO ROLE FUIDP_ANALYTICS_RW;     -- RW builds on READ
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA FUIDP.ANALYTICS TO ROLE FUIDP_ANALYTICS_RW;

-- 2) FUNCTIONAL roles — the WHO (granted access roles, never raw privileges):
CREATE ROLE IF NOT EXISTS ADVISOR;     GRANT ROLE FUIDP_ANALYTICS_READ TO ROLE ADVISOR;
CREATE ROLE IF NOT EXISTS ANALYST;     GRANT ROLE FUIDP_ANALYTICS_READ TO ROLE ANALYST;
                                       GRANT ROLE FUIDP_RAW_READ       TO ROLE ANALYST;
CREATE ROLE IF NOT EXISTS COMPLIANCE;  GRANT ROLE FUIDP_ANALYTICS_READ TO ROLE COMPLIANCE;
                                       GRANT ROLE FUIDP_RAW_READ       TO ROLE COMPLIANCE;
CREATE ROLE IF NOT EXISTS ENGINEER;    GRANT ROLE FUIDP_ANALYTICS_RW   TO ROLE ENGINEER;
                                       GRANT ROLE FUIDP_RAW_READ       TO ROLE ENGINEER;

-- Warehouse usage for all personas:
GRANT USAGE ON WAREHOUSE WH_ANALYTICS TO ROLE ADVISOR;
GRANT USAGE ON WAREHOUSE WH_ANALYTICS TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE WH_ANALYTICS TO ROLE COMPLIANCE;
GRANT USAGE ON WAREHOUSE WH_ANALYTICS TO ROLE ENGINEER;

-- 3) Hierarchy hygiene + give YOURSELF the personas (for Lab 19's role-switching):
GRANT ROLE ADVISOR, ANALYST, COMPLIANCE, ENGINEER TO ROLE SYSADMIN;
GRANT ROLE ADVISOR    TO USER CORPORATE;
GRANT ROLE ANALYST    TO USER CORPORATE;
GRANT ROLE COMPLIANCE TO USER CORPORATE;
GRANT ROLE ENGINEER   TO USER CORPORATE;