USE SCHEMA FIDELITY_ATLAS.RAW;


CREATE OR REPLACE TABLE RAW_EXECUTIONS (
  RECORD_METADATA VARIANT,
  RECORD_CONTENT  VARIANT
);


CREATE USER IF NOT EXISTS streaming_user
  COMMENT = 'Service user for streaming ingest (key-pair auth)';

ALTER USER streaming_user SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApykHpx1xMtaZTHcl0SO7
TdEuuEjDr+p+W6932vvLks8rCNN+RsJqBsxyMs43kNbMaqwDg/QOyE2XQUJVqs6L
8FIpBSrbm+wJbICIUFB8+NASDb5KZuzI/nCcYbv++v2Qe6HVeJUnKfQBuyexBh9x
MlZVuo0190eNvg24fx/1myIeAxISt5acPtpaUb4/V2jCo3bs3zAk8Fj1EN4csfiA
/oiKhYkhVMTalUhPQ39qz5RThZ995Zy2bLjrO63MPPQhz+vX/9eIzyKSVitccMcI
sno4w/CPUzjaH3AsQQ6hrTaL5tnE3zBrc08ouEEs0wSRsGBXN/wADWmQXJF5Tur7
0wIDAQAB';

GRANT USAGE ON DATABASE FIDELITY_ATLAS TO USER streaming_user;

GRANT USAGE ON SCHEMA FIDELITY_ATLAS.RAW TO USER streaming_user;

GRANT INSERT, SELECT ON TABLE RAW_EXECUTIONS TO USER streaming_user;

CREATE ROLE IF NOT EXISTS ATLAS_ENGINEER;

GRANT ROLE ATLAS_ENGINEER TO USER streaming_user;


GRANT USAGE ON DATABASE FIDELITY_ATLAS TO ROLE ATLAS_ENGINEER;

GRANT USAGE ON SCHEMA FIDELITY_ATLAS.RAW TO ROLE ATLAS_ENGINEER;

GRANT INSERT, SELECT ON TABLE RAW_EXECUTIONS TO ROLE ATLAS_ENGINEER;


SELECT COUNT(*) FROM RAW_EXECUTIONS;

SELECT RECORD_CONTENT:symbol::string AS sym,
       RECORD_CONTENT:side::string   AS side,
       RECORD_CONTENT:price::number(12,2) AS px,
       RECORD_CONTENT:fillStatus::string  AS status
FROM RAW_EXECUTIONS LIMIT 10;


SHOW CHANNELS IN TABLE RAW_EXECUTIONS; -- streaming channels (empty if connector never connected)



INSERT INTO FIDELITY_ATLAS.ANALYTICS.FACT_EXECUTIONS
 (EVENT_ID, SECURITY_KEY, VENUE_KEY, DATE_KEY, EVENT_TS,
  SIDE, ORDER_TYPE, FILL_STATUS, PRICE, QUANTITY, TRADER)
SELECT
  e.RECORD_CONTENT:eventId::string,
  s.SECURITY_KEY, v.VENUE_KEY,
  TO_NUMBER(TO_CHAR(e.RECORD_CONTENT:eventTs::timestamp_ntz,'YYYYMMDD')),
  e.RECORD_CONTENT:eventTs::timestamp_ntz,
  e.RECORD_CONTENT:side::string,
  e.RECORD_CONTENT:orderType::string,
  e.RECORD_CONTENT:fillStatus::string,
  e.RECORD_CONTENT:price::number(12,2),
  e.RECORD_CONTENT:quantity::number,
  e.RECORD_CONTENT:trader::string
FROM FIDELITY_ATLAS.RAW.RAW_EXECUTIONS e
JOIN FIDELITY_ATLAS.ANALYTICS.DIM_SECURITY s ON s.SYMBOL = e.RECORD_CONTENT:symbol::string
JOIN FIDELITY_ATLAS.ANALYTICS.DIM_VENUE    v ON v.VENUE_CODE = e.RECORD_CONTENT:venue::string;


SELECT COUNT(*) FROM FIDELITY_ATLAS.ANALYTICS.FACT_EXECUTIONS;