CREATE DATABASE IF NOT EXISTS FIDELITY_ATLAS;


CREATE SCHEMA  IF NOT EXISTS FIDELITY_ATLAS.RAW;
CREATE SCHEMA  IF NOT EXISTS FIDELITY_ATLAS.ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS ATLAS_LOAD_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE DATABASE FIDELITY_ATLAS;
USE SCHEMA RAW;
USE WAREHOUSE ATLAS_LOAD_WH;


USE SCHEMA FIDELITY_ATLAS.RAW;

CREATE OR REPLACE TABLE TICKS (
  SYMBOL      STRING,
  TRADE_DATE  DATE,
  TICK_TS     TIMESTAMP_NTZ,
  LAST_PRICE  NUMBER(12,2),
  BID         NUMBER(12,2),
  ASK         NUMBER(12,2),
  TRADE_SIZE  NUMBER(10,0),
  VENUE       STRING
);

CREATE OR REPLACE STAGE ATLAS_LOCAL_STAGE
  FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');


COPY INTO TICKS
FROM @ATLAS_LOCAL_STAGE/ticks_history.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
ON_ERROR = 'ABORT_STATEMENT';


SELECT COUNT(*) AS rows_loaded, MIN(TRADE_DATE), MAX(TRADE_DATE) FROM TICKS;

ALTER WAREHOUSE ATLAS_LOAD_WH RESUME IF SUSPENDED;


USE WAREHOUSE ATLAS_LOAD_WH;
USE DATABASE FIDELITY_ATLAS;
USE SCHEMA RAW;

SELECT SYMBOL, AVG(LAST_PRICE) AS avg_px, SUM(TRADE_SIZE) AS vol
FROM TICKS
WHERE SYMBOL = 'NVDA'
  AND TRADE_DATE BETWEEN '2024-02-05' AND '2024-02-09'
GROUP BY SYMBOL;


SELECT
  query_id, partitions_scanned, partitions_total,
  ROUND(100*partitions_scanned/NULLIF(partitions_total,0),1) AS pct_scanned
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE query_text ILIKE '%NVDA%' AND query_text ILIKE '%2024-02-05%'
ORDER BY start_time DESC
LIMIT 5;

SELECT SYSTEM$CLUSTERING_INFORMATION('TICKS', '(TRADE_DATE, SYMBOL)');

ALTER TABLE TICKS CLUSTER BY (TRADE_DATE, SYMBOL);

CREATE OR REPLACE TABLE TICKS_CLUSTERED
  CLUSTER BY (TRADE_DATE, SYMBOL)
AS
SELECT * FROM TICKS ORDER BY TRADE_DATE, SYMBOL;


SELECT SYMBOL, AVG(LAST_PRICE) AS avg_px, SUM(TRADE_SIZE) AS vol
FROM TICKS_CLUSTERED
WHERE SYMBOL = 'NVDA'
  AND TRADE_DATE BETWEEN '2024-02-05' AND '2024-02-09'
GROUP BY SYMBOL;

SELECT SYSTEM$CLUSTERING_INFORMATION('TICKS_CLUSTERED', '(TRADE_DATE, SYMBOL)');
