CREATE OR REPLACE RESOURCE MONITOR rm_fuidp_training
  CREDIT_QUOTA = 5  FREQUENCY = DAILY  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE WH_ANALYTICS SET RESOURCE_MONITOR = rm_fuidp_training;
SHOW RESOURCE MONITORS;