ALTER SESSION SET QUERY_TAG = 'team:risk;pipeline:fuidp;lab:15';
SELECT COUNT(*) FROM FUIDP.RAW.trades_large WHERE symbol='NVDA';
ALTER SESSION UNSET QUERY_TAG;

-- The chargeback query (note: ACCOUNT_USAGE can lag ~45 min):
SELECT QUERY_TAG, COUNT(*) AS queries,
       SUM(TOTAL_ELAPSED_TIME)/1000 AS total_seconds,
       SUM(BYTES_SCANNED)/POWER(1024,3) AS gb_scanned
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME > DATEADD('day',-1,CURRENT_TIMESTAMP()) AND QUERY_TAG <> ''
GROUP BY QUERY_TAG ORDER BY total_seconds DESC;