CREATE DATABASE IF NOT EXISTS FIDELITY_ATLAS;

CREATE SCHEMA  IF NOT EXISTS FIDELITY_ATLAS.RAW;
CREATE SCHEMA  IF NOT EXISTS FIDELITY_ATLAS.ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS ATLAS_LOAD_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE DATABASE FIDELITY_ATLAS;
USE SCHEMA RAW;
USE WAREHOUSE ATLAS_LOAD_WH;
