USE SCHEMA FIDELITY_ATLAS.RAW;

CREATE OR REPLACE TABLE TICKS (
  SYMBOL      STRING,
  TRADE_DATE  DATE,
  TICK_TS     TIMESTAMP_NTZ,
  LAST_PRICE  NUMBER(12,2),
  BID         NUMBER(12,2),
  ASK         NUMBER(12,2),
  TRADE_SIZE  NUMBER(10,0),
  VENUE       STRING
);

CREATE OR REPLACE STAGE ATLAS_LOCAL_STAGE
  FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');

COPY INTO TICKS
FROM @ATLAS_LOCAL_STAGE/ticks_history.csv
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
ON_ERROR = 'ABORT_STATEMENT';

SELECT COUNT(*) AS rows_loaded, MIN(TRADE_DATE), MAX(TRADE_DATE) FROM TICKS;


SELECT * FROM TICKS;
