USE SCHEMA FIDELITY_ATLAS.ANALYTICS;


CREATE OR REPLACE TABLE DIM_SECURITY (
  SECURITY_KEY  INT AUTOINCREMENT START 1 INCREMENT 1,
  SYMBOL        STRING NOT NULL,
  COMPANY_NAME  STRING,
  SECTOR        STRING,
  CONSTRAINT pk_dim_security PRIMARY KEY (SECURITY_KEY)
);

CREATE OR REPLACE TABLE DIM_VENUE (
  VENUE_KEY  INT AUTOINCREMENT START 1 INCREMENT 1,
  VENUE_CODE STRING NOT NULL,
  VENUE_NAME STRING,
  CONSTRAINT pk_dim_venue PRIMARY KEY (VENUE_KEY)
);

CREATE OR REPLACE TABLE DIM_DATE (
  DATE_KEY   INT,            -- yyyymmdd
  CAL_DATE   DATE,
  YEAR       INT, QUARTER INT, MONTH INT, DAY INT,
  DAY_OF_WEEK INT, IS_WEEKDAY BOOLEAN,
  CONSTRAINT pk_dim_date PRIMARY KEY (DATE_KEY)
);


INSERT INTO DIM_SECURITY (SYMBOL, COMPANY_NAME, SECTOR)
SELECT DISTINCT t.SYMBOL,
       NULL, NULL          -- enriched below from a small security master
FROM FIDELITY_ATLAS.RAW.TICKS_CLUSTERED t;


MERGE INTO DIM_SECURITY d
USING (
  SELECT * FROM VALUES
    ('FNF','Fidelity National Financial','Financials'),
    ('AAPL','Apple Inc.','Technology'),
    ('MSFT','Microsoft Corp.','Technology'),
    ('JPM','JPMorgan Chase & Co.','Financials'),
    ('XOM','Exxon Mobil Corp.','Energy'),
    ('TSLA','Tesla Inc.','Consumer'),
    ('NVDA','NVIDIA Corp.','Technology'),
    ('BRKB','Berkshire Hathaway B','Financials')
  AS m(SYMBOL,COMPANY_NAME,SECTOR)
) s ON d.SYMBOL = s.SYMBOL
WHEN MATCHED THEN UPDATE SET d.COMPANY_NAME=s.COMPANY_NAME, d.SECTOR=s.SECTOR;


INSERT INTO DIM_VENUE (VENUE_CODE, VENUE_NAME)
SELECT * FROM VALUES
  ('NYSE','New York Stock Exchange'),('NASDAQ','NASDAQ'),
  ('CBOE','Cboe Options Exchange'),('ARCA','NYSE Arca'),('BATS','Cboe BZX');


INSERT INTO DIM_DATE
SELECT DISTINCT
  TO_NUMBER(TO_CHAR(d,'YYYYMMDD')) AS DATE_KEY, d AS CAL_DATE,
  YEAR(d), QUARTER(d), MONTH(d), DAY(d),
  DAYOFWEEK(d), DAYOFWEEK(d) BETWEEN 1 AND 5
FROM (
  SELECT DISTINCT TRADE_DATE AS d FROM FIDELITY_ATLAS.RAW.TICKS_CLUSTERED
);



CREATE OR REPLACE TABLE FACT_QUOTES (
  QUOTE_KEY    INT AUTOINCREMENT,
  SECURITY_KEY INT, VENUE_KEY INT, DATE_KEY INT,
  TICK_TS      TIMESTAMP_NTZ,
  LAST_PRICE   NUMBER(12,2), BID NUMBER(12,2), ASK NUMBER(12,2),
  SPREAD       NUMBER(12,4), TRADE_SIZE NUMBER(10,0)
);

-- Grain: one row per executed trade (Lab 4 fills this).
CREATE OR REPLACE TABLE FACT_TRADES (
  TRADE_KEY    INT AUTOINCREMENT,
  TRADE_ID     NUMBER,           -- natural key from venue file
  SECURITY_KEY INT, VENUE_KEY INT, DATE_KEY INT,
  EXEC_TS      TIMESTAMP_NTZ,
  SIDE         STRING, PRICE NUMBER(12,2), QUANTITY NUMBER(12,0),
  NOTIONAL     NUMBER(18,2)
);

-- Grain: one row per option-contract snapshot (Lab 5 fills this).
CREATE OR REPLACE TABLE FACT_OPTION_QUOTES (
  OPT_KEY      INT AUTOINCREMENT,
  SECURITY_KEY INT, DATE_KEY INT,
  CONTRACT_ID  STRING, OPT_TYPE STRING, STRIKE NUMBER(12,2),
  EXPIRATION   DATE, DAYS_TO_EXPIRY INT,
  LAST_PRICE   NUMBER(12,2), BID NUMBER(12,2), ASK NUMBER(12,2),
  VOLUME NUMBER, OPEN_INTEREST NUMBER,
  DELTA NUMBER(8,4), GAMMA NUMBER(8,4), THETA NUMBER(8,4),
  VEGA NUMBER(8,4), IMPLIED_VOL NUMBER(8,4)
);

-- Grain: one row per live execution event (Lab 7 fills this).
CREATE OR REPLACE TABLE FACT_EXECUTIONS (
  EXEC_KEY     INT AUTOINCREMENT,
  EVENT_ID     STRING,
  SECURITY_KEY INT, VENUE_KEY INT, DATE_KEY INT,
  EVENT_TS     TIMESTAMP_NTZ,
  SIDE STRING, ORDER_TYPE STRING, FILL_STATUS STRING,
  PRICE NUMBER(12,2), QUANTITY NUMBER(12,0), TRADER STRING
);

INSERT INTO FACT_QUOTES
  (SECURITY_KEY, VENUE_KEY, DATE_KEY, TICK_TS, LAST_PRICE, BID, ASK, SPREAD, TRADE_SIZE)
SELECT s.SECURITY_KEY, v.VENUE_KEY,
       TO_NUMBER(TO_CHAR(t.TRADE_DATE,'YYYYMMDD')),
       t.TICK_TS, t.LAST_PRICE, t.BID, t.ASK, (t.ASK - t.BID), t.TRADE_SIZE
FROM FIDELITY_ATLAS.RAW.TICKS_CLUSTERED t
JOIN DIM_SECURITY s ON s.SYMBOL = t.SYMBOL
JOIN DIM_VENUE    v ON v.VENUE_CODE = t.VENUE;


SELECT COUNT(*) FROM FACT_QUOTES;

SELECT * FROM FACT_QUOTES
LIMIT 10;