USE SCHEMA FIDELITY_ATLAS.RAW;


CREATE OR REPLACE TABLE RAW_EXECUTIONS (
  RECORD_METADATA VARIANT,
  RECORD_CONTENT  VARIANT
);

CREATE ROLE IF NOT EXISTS ATLAS_ENGINEER;

CREATE USER IF NOT EXISTS streaming_user
  COMMENT = 'Service user for streaming ingest (key-pair auth)';

GRANT ROLE ATLAS_ENGINEER TO USER streaming_user;

GRANT USAGE ON DATABASE FIDELITY_ATLAS TO ROLE ATLAS_ENGINEER;
GRANT USAGE ON SCHEMA FIDELITY_ATLAS.RAW TO ROLE ATLAS_ENGINEER;
GRANT INSERT, SELECT ON TABLE RAW_EXECUTIONS TO ROLE ATLAS_ENGINEER;

ALTER USER streaming_user SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoTHs3grbkbPIBgsErDc0CVJVhU42KH2zqX23/EjsKIIv6ypcEbLTWE+qWzva2ywvWaYk1Ft5ieBXPYPNP+8Y2oMvQGkOunqr1Sz6GbvHkwyr5FuoL76WiwH6OaZ5Rz0QGtjfHrbRRxC39yIxM6D63hcu941PZ648zSVzhGmNOLExu+tvKG9k7FuStMPv082HQrbrN8LFK4UCQhLsmqqILPH8ShrQI5V8T1ioU6+O4f8Y1LbydoTNloA12wuvprYVzphFud/9MF4Dma/ArKJooLx/q6ixfmLvrULAjsfAFKAInTIHUqosvKvp2lRBgityMFkBxj1Ie2jEiObhhQRGQwIDAQAB';


SELECT * FROM RAW_EXECUTIONS
LIMIT 10;

SELECT RECORD_CONTENT:symbol::string AS sym,
       RECORD_CONTENT:side::string   AS side,
       RECORD_CONTENT:price::number(12,2) AS px,
       RECORD_CONTENT:fillStatus::string  AS status
FROM RAW_EXECUTIONS LIMIT 10;


SHOW CHANNELS IN TABLE RAW_EXECUTIONS; -- streaming channels (empty if connector never connected)



INSERT INTO FIDELITY_ATLAS.ANALYTICS.FACT_EXECUTIONS
 (EVENT_ID, SECURITY_KEY, VENUE_KEY, DATE_KEY, EVENT_TS,
  SIDE, ORDER_TYPE, FILL_STATUS, PRICE, QUANTITY, TRADER)
SELECT
  e.RECORD_CONTENT:eventId::string,
  s.SECURITY_KEY, v.VENUE_KEY,
  TO_NUMBER(TO_CHAR(e.RECORD_CONTENT:eventTs::timestamp_ntz,'YYYYMMDD')),
  e.RECORD_CONTENT:eventTs::timestamp_ntz,
  e.RECORD_CONTENT:side::string,
  e.RECORD_CONTENT:orderType::string,
  e.RECORD_CONTENT:fillStatus::string,
  e.RECORD_CONTENT:price::number(12,2),
  e.RECORD_CONTENT:quantity::number,
  e.RECORD_CONTENT:trader::string
FROM FIDELITY_ATLAS.RAW.RAW_EXECUTIONS e
JOIN FIDELITY_ATLAS.ANALYTICS.DIM_SECURITY s ON s.SYMBOL = e.RECORD_CONTENT:symbol::string
JOIN FIDELITY_ATLAS.ANALYTICS.DIM_VENUE    v ON v.VENUE_CODE = e.RECORD_CONTENT:venue::string;


SELECT COUNT(*) FROM FIDELITY_ATLAS.ANALYTICS.FACT_EXECUTIONS;